name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    container:
      image: node:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Jest
        run: npm install jest

      - name: Run Unit Tests
        run: npm run test